service: template-serverless-v3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  # esbuild configuration
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    
  # serverless-offline configuration
  serverless-offline:
    noAuth: true
    noTimeout: true
    noSponsor: true    

functions:
  hello:
    handler: src/index.handler
    events:
      - httpApi:
          path: /hello
          method: get
