import type * as aws from '@pulumi/aws';
import * as awsx from '@pulumi/awsx';
import * as eks from '@pulumi/eks';
import * as k8s from '@pulumi/kubernetes';
import * as pulumi from '@pulumi/pulumi';

// Initialize Pulumi configuration to read variables from the current stack
const config = new pulumi.Config();
const isLocal = config.getBoolean('isLocal') ?? false;

// Define output variables for later export
let kubeconfig: pulumi.Output<any>;
let localProvider: k8s.Provider | undefined;
let vpcId: pulumi.Output<string> | undefined;

if (isLocal) {
  /**
   * LOCAL MODE (Minikube / K3s)
   * Does not provision infrastructure on AWS. Assumes the cluster is already running
   * and the kubectl context is correctly configured.
   */

  // Define kubeconfig as null or empty string to force the use of the default local context (~/.kube/config)
  kubeconfig = pulumi.output('using-default-local-context');

  // Instantiates the local Kubernetes provider to manage resources within Minikube/K3s
  localProvider = new k8s.Provider('local-provider', {
    suppressDeprecationWarnings: true,
  });

  // Here you would add K8s resources (Deployments, Services) using the localProvider
} else {
  /**
   * PRODUCTION MODE (AWS EKS)
   * Provisions all network infrastructure and the managed cluster on AWS.
   */

  // Network configurations extracted from Pulumi.dev.yaml or default values
  const vpcNetworkCidr = config.get('vpcNetworkCidr') || '10.0.0.0/16';

  // Creation of an isolated VPC with DNS support for the cluster
  const eksVpc = new awsx.ec2.Vpc('eks-vpc', {
    enableDnsHostnames: true,
    cidrBlock: vpcNetworkCidr,
  });

  // Provisioning of the EKS cluster with API authentication and private subnets for the nodes
  const eksCluster = new eks.Cluster('eks-cluster', {
    vpcId: eksVpc.vpcId,
    authenticationMode: eks.AuthenticationMode.Api,
    publicSubnetIds: eksVpc.publicSubnetIds,
    privateSubnetIds: eksVpc.privateSubnetIds,
    instanceType: (config.get('eksNodeInstanceType') || 't3.medium') as aws.ec2.InstanceType,
    desiredCapacity: config.getNumber('desiredClusterSize') || 3,
    minSize: config.getNumber('minClusterSize') || 3,
    maxSize: config.getNumber('maxClusterSize') || 6,
    nodeAssociatePublicIpAddress: false,
    endpointPrivateAccess: false,
    endpointPublicAccess: true,
  });

  // Captures the kubeconfig generated by EKS and the ID of the created VPC
  kubeconfig = eksCluster.kubeconfig;
  vpcId = eksVpc.vpcId;
}

/**
 * Values that can be accessed via `pulumi stack output` or consumed by other stacks.
 */
export {kubeconfig, localProvider, vpcId};
